name: (Prod) Plan & Apply Terraform

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  plan:
    name: Terraform Plan

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
